export default {
  INIT_POST_OFFICES_COMPONENT: 'INIT_POST_OFFICES_COMPONENT',
  FETCH_POST_OFFICES_SUCCESS: 'FETCH_POST_OFFICES_SUCCESS',
  FETCH_POST_OFFICES_FAILURE: 'FETCH_POST_OFFICES_FAILURE',
  CREATE_POST_OFFICE_DATA: 'CREATE_POST_OFFICE_DATA',
  UPDATE_POST_OFFICE_DATA: 'UPDATE_POST_OFFICE_DATA',
  DELETE_POST_OFFICE_DATA: 'DELETE_POST_OFFICE_DATA',
  OPEN_CREATE_OR_UPDATE_MODAL: 'OPEN_CREATE_OR_UPDATE_MODAL',
  CLOSE_CREATE_OR_UPDATE_MODAL: 'CLOSE_CREATE_OR_UPDATE_MODAL',
  SUBMIT_CREATE_OR_UPDATE: 'SUBMIT_CREATE_OR_UPDATE',
  SUBMIT_CREATE_OR_UPDATE_SUCCESS: 'SUBMIT_CREATE_OR_UPDATE_SUCCESS',
  SUBMIT_CREATE_OR_UPDATE_FAILURE: 'SUBMIT_CREATE_OR_UPDATE_FAILURE',
  DELETE_POST_OFFICE_SUCCESS: 'DELETE_POST_OFFICE_SUCCESS',
  DELETE_POST_OFFICE_FAILURE: 'DELETE_POST_OFFICE_FAILURE'
};