export default {
  INIT_SHIPMENTS_COMPONENT: 'INIT_SHIPMENTS_COMPONENT',
  FETCH_SHIPMENTS_SUCCESS: 'FETCH_SHIPMENTS_SUCCESS',
  FETCH_SHIPMENTS_FAILURE: 'FETCH_SHIPMENTS_FAILURE',
  CREATE_SHIPMENT_DATA: 'CREATE_SHIPMENT_DATA',
  UPDATE_SHIPMENT_DATA: 'UPDATE_SHIPMENT_DATA',
  DELETE_SHIPMENT_DATA: 'DELETE_SHIPMENT_DATA',
  OPEN_CREATE_OR_UPDATE_MODAL: 'OPEN_CREATE_OR_UPDATE_MODAL',
  CLOSE_CREATE_OR_UPDATE_MODAL: 'CLOSE_CREATE_OR_UPDATE_MODAL',
  SUBMIT_CREATE_OR_UPDATE: 'SUBMIT_CREATE_OR_UPDATE',
  SUBMIT_CREATE_OR_UPDATE_SUCCESS: 'SUBMIT_CREATE_OR_UPDATE_SUCCESS',
  SUBMIT_CREATE_OR_UPDATE_FAILURE: 'SUBMIT_CREATE_OR_UPDATE_FAILURE',
  DELETE_SHIPMENT_SUCCESS: 'DELETE_SHIPMENT_SUCCESS',
  DELETE_SHIPMENT_FAILURE: 'DELETE_SHIPMENT_FAILURE',
  FETCH_POST_OFFICES_SUCCESS: 'FETCH_POST_OFFICES_SUCCESS',
  FETCH_POST_OFFICES_FAILURE: 'FETCH_POST_OFFICES_FAILURE',
  SET_FILTER_DATA: 'SET_FILTER_DATA'
};